# Generated by Django 3.0.6 on 2020-05-16 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat2user',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='chat2user',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_id',
            new_name='sender',
        ),
    ]
