# Generated by Django 3.0.6 on 2020-05-17 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat_app', '0005_user2unreadmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
