# Generated by Django 3.0.6 on 2020-05-16 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0002_auto_20200516_1043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='is_orientation',
            new_name='is_orientationable',
        ),
    ]
