# Generated by Django 2.2.10 on 2020-05-18 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0003_auto_20200516_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('content', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Test2User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=None, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.TestsModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section2Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.SectionModel')),
                ('tests', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses_app.TestsModel')),
            ],
        ),
        migrations.CreateModel(
            name='Section2Sections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.SectionModel')),
                ('sections', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_of_this_section', to='courses_app.SectionModel')),
            ],
        ),
        migrations.CreateModel(
            name='Section2Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses_app.PagesModel')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.SectionModel')),
            ],
        ),
        migrations.CreateModel(
            name='Section2Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documents', models.FileField(upload_to='documents/')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.SectionModel')),
            ],
        ),
    ]
