# Generated by Django 2.2.10 on 2020-05-18 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_coursemodel_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section2pages',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='section2pages',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section2tests',
            name='section',
        ),
        migrations.RemoveField(
            model_name='section2tests',
            name='tests',
        ),
        migrations.AddField(
            model_name='documentsmodel',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses_app.SectionModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagesmodel',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses_app.SectionModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsmodel',
            name='section',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses_app.SectionModel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Section2Documents',
        ),
        migrations.DeleteModel(
            name='Section2Pages',
        ),
        migrations.DeleteModel(
            name='Section2Tests',
        ),
    ]
