# Generated by Django 2.2.10 on 2020-05-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0007_auto_20200518_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckOrRadioAnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right', models.BooleanField(default=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2)),
                ('rating', models.IntegerField()),
                ('question', models.TextField()),
                ('hint', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='testsmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testsmodel',
            name='number_of_questions',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testsmodel',
            name='time_restriction',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='testsmodel',
            name='tries',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Question2Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.QuestionModel')),
            ],
        ),
        migrations.CreateModel(
            name='Question2Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses_app.CheckOrRadioAnswerModel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.QuestionModel')),
            ],
        ),
    ]
