# Generated by Django 2.2.10 on 2020-05-19 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0011_auto_20200519_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkorradioanswermodel',
            old_name='answer',
            new_name='is_correct',
        ),
        migrations.RenameField(
            model_name='checkorradioanswermodel',
            old_name='right',
            new_name='text',
        ),
    ]
