# Generated by Django 2.2.10 on 2020-05-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0012_auto_20200519_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkorradioanswermodel',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkorradioanswermodel',
            name='text',
            field=models.TextField(),
        ),
    ]
