# Generated by Django 2.2.10 on 2020-05-19 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses_app', '0013_auto_20200519_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateTimeField(auto_now_add=True)),
                ('date_submited', models.DateTimeField(default=None, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.TestsModel')),
            ],
        ),
        migrations.CreateModel(
            name='Try2Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None, null=True)),
                ('answer_file', models.FileField(upload_to='answers/')),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.QuestionModel')),
                ('try_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.TriesModel')),
            ],
        ),
    ]
