# Generated by Django 2.2.10 on 2020-05-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0014_triesmodel_try2question'),
    ]

    operations = [
        migrations.AddField(
            model_name='triesmodel',
            name='rated',
            field=models.BooleanField(default=False),
        ),
    ]
