# Generated by Django 2.2.10 on 2020-05-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0015_triesmodel_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='try2question',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='try2question',
            name='rate',
            field=models.FloatField(default=None, null=True),
        ),
    ]
