# Generated by Django 2.2.10 on 2020-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0016_auto_20200520_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='rating',
            field=models.FloatField(),
        ),
    ]
