# Generated by Django 2.2.10 on 2020-05-20 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0017_auto_20200520_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='try2question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='try2question',
            name='answer_file',
        ),
        migrations.CreateModel(
            name='Try2QuestionAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default=None, null=True)),
                ('answer_file', models.FileField(upload_to='answers/')),
                ('try2question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.Try2Question')),
            ],
        ),
    ]
