# Generated by Django 2.2.10 on 2020-05-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0018_auto_20200520_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='try2question',
            name='answer',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='try2question',
            name='answer_file',
            field=models.FileField(default=None, upload_to='answers/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Try2QuestionAnswers',
        ),
    ]
