# Generated by Django 2.2.10 on 2020-05-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0020_auto_20200520_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='triesmodel',
            name='max_rating',
        ),
        migrations.RemoveField(
            model_name='triesmodel',
            name='rating',
        ),
        migrations.AlterField(
            model_name='try2question',
            name='answer_file',
            field=models.FileField(null=True, upload_to='answers/'),
        ),
    ]
