# Generated by Django 2.2.10 on 2020-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0021_auto_20200520_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='triesmodel',
            name='max_rating',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='triesmodel',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
