# Generated by Django 2.2.10 on 2020-05-21 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0023_auto_20200521_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triesmodel',
            name='max_rating',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='triesmodel',
            name='rating',
            field=models.FloatField(default=None, null=True),
        ),
    ]
