# Generated by Django 2.2.10 on 2020-05-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0024_auto_20200521_0645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test2User',
        ),
    ]
