# Generated by Django 3.0.6 on 2020-05-26 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0026_auto_20200527_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionmodel',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
