# Generated by Django 3.0.6 on 2020-05-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0027_auto_20200527_0236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsmodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pagesmodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='testsmodel',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
