# Generated by Django 3.0.5 on 2020-05-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_auto_20200516_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='eesuser',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
