# Generated by Django 3.0.6 on 2020-05-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0007_eesuser_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='eesuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
