# Generated by Django 3.0.6 on 2020-05-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0008_eesuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eesuser',
            name='avatar',
            field=models.ImageField(default='/static/no_img.png', upload_to='avatars'),
        ),
    ]
