# Generated by Django 3.0.6 on 2020-05-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0009_auto_20200516_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eesuser',
            name='avatar',
            field=models.ImageField(default='no_img.png', upload_to='avatars'),
        ),
    ]
