# Generated by Django 3.0.6 on 2020-05-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0011_auto_20200516_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eesuser',
            name='avatar',
            field=models.ImageField(default='no_img.png', null=True, upload_to='avatars'),
        ),
    ]
