# Generated by Django 3.0.5 on 2020-05-16 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_auto_20200516_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsmodel',
            old_name='publisher_id',
            new_name='publisher',
        ),
    ]
