# Generated by Django 3.0.6 on 2020-05-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0005_auto_20200517_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsmodel',
            name='publish_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
